//
//  PurchaseOptions.swift
//  Qonversion
//

import Foundation

extension Qonversion {

    /// Additional options for the purchase process. Store-affecting options
    /// (quantity, promo offer) are applied to the App Store purchase;
    /// association options (contextKeys, screenUid) are attached to the
    /// purchase report.
    public struct PurchaseOptions {

        /// Quantity of the product purchasing. Use for consumable in-app products.
        public let quantity: Int

        /// Context keys associated with the purchase. Use to associate the
        /// purchase with a concrete remote config.
        public let contextKeys: [String]?

        /// Screen UID associated with the purchase. Use to track which screen
        /// initiated the purchase.
        public let screenUid: String?

        /// Promo offer details. Use to make a purchase with a promo offer.
        public let promoOffer: PromotionalOffer?

        public init(quantity: Int = 1, contextKeys: [String]? = nil, screenUid: String? = nil, promoOffer: PromotionalOffer? = nil) {
            self.quantity = quantity
            self.contextKeys = contextKeys
            self.screenUid = screenUid
            self.promoOffer = promoOffer
        }
    }

    /// A signed promotional offer to apply to the purchase. The signature is
    /// generated by your server with the App Store subscription key.
    public struct PromotionalOffer {

        public let offerId: String
        public let keyId: String
        public let nonce: UUID
        public let signature: Data
        public let timestamp: Int

        public init(offerId: String, keyId: String, nonce: UUID, signature: Data, timestamp: Int) {
            self.offerId = offerId
            self.keyId = keyId
            self.nonce = nonce
            self.signature = signature
            self.timestamp = timestamp
        }
    }
}
