
PROJECT_NAME = "_Pods"
PROJECT_SCHEME = "QonversionTests"
XCODE_PROJECT = "./#{PROJECT_NAME}.xcodeproj"

lane :tests do
  run_tests(
    scheme: PROJECT_SCHEME,
    devices: ["iPhone 7", "iPhone 11"]
  )
end
