name: Planned integration tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  tests:
    runs-on: macos-latest
    
    concurrency:
      group: ios_integration_tests
      cancel-in-progress: true
    
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '26.0.1'
      - uses: actions/checkout@v2
      
      - name: Cache CocoaPods
        uses: actions/cache@v3
        with:
          path: |
            Pods
            ~/Library/Caches/CocoaPods
            ~/.cocoapods/repos
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      
      - name: Set Outager url
        run: |
          fastlane set_outager_url url:${{ secrets.OUTAGER_URL }}

      - name: Tests
        run: |
          fastlane integration_tests
