name: Planned tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  tests:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Tests
        run: swift test
