name: Manual Minor Prerelease

on:
  workflow_dispatch
    
jobs:
  patch-minor:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Minor
        run: |
          fastlane minor
