name: Manual Minor Prerelease

on:
  workflow_dispatch
    
jobs:
  patch-minor:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Minor
        run: |
          fastlane minor
